cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('remove/', views.cart_remove, name='cart_clear'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'
urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

ishop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('rosetta/', include('rosetta.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('admin/order/<int:order_id>', views.admin_order_detail, name='admin_order_detail'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='quantity', max_value=99)
    update = forms.BooleanField(label='upd', required=False, initial=False)

cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def cart_remove(request, product_id=None):
    cart = Cart(request)
    if product_id:
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
    else:
        cart.remove()
    return redirect('cart:cart_detail')


def cart_clear(request):
    cart = Cart(request)
    cart.remove()
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    categories = Category.objects.all()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True
                                                                   })
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_apply_form': coupon_apply_form,
                                                'categories': categories
                                                })

templates/cart/detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Your shopping cart' %}{% endblock %}
{% block content %}
    <div class="site-section">
        <div class="container">
            <h1 align="center" style="padding-bottom: 50px">{% trans 'Your cart' %}</h1>
        
        {% if cart %}
            <div class="row mb-5">
                <div class="site-blocks-table" >
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th class="product-thumbnail">{% trans 'Image' %}</th>
                            <th class="product-name">{% trans 'Product' %}</th>
                            <th class="product-price">{% trans 'Price' %}</th>
                            <th class="product-quantity">{% trans 'Quantity' %}</th>
                            <th class="product-total">{% trans 'Total' %}</th>
                            <th class="product-remove">{% trans 'Remove' %}</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for item in cart %}
                            {% with product=item.product %}
                                <tr>
                                    <td class="product-thumbnail">
                                        <a href="{{ product.get_absolute_url}}">
                                            <img src="{{ product.image.url }}" alt="Image" class="img-fluid">
                                        </a>
                                    </td>
                                    <td class="product-name" >{{ product.name }}</td>
                                    <td>{{ item.price }}</td>
                                    <td>
                                        <div class="input-group mb-3" style="max-width: 100px">

                                            <form method="post" action="{% url 'cart:cart_add' product.id %}">
                                                    {% csrf_token %}
                                                <input type="hidden" name="update" id="upd" value="True">
                                                <input type="number" class="form-control text-center"
                                                       aria-label="quantity" id="quantity" name="quantity"
                                                       value="{{ item.quantity }}" min="1">
                                                <input type="submit" value="{% trans 'Update' %}" class="btn btn-primary btn-md px-4" >
                                            </form>

                                        </div>
                                    </td>
                                    <td>{{ item.total_price }}</td>
                                    <td>
                                        <a href="{% url "cart:cart_remove" product.id %}"
                                           class="btn btn-primary height-auto btn-sm icon-trash"></a>
                                    </td>
                                </tr>
                            {% endwith %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
                  {% else %}
            <div class="text-xl-center">
                <br>
                <i class="icon-shopping-cart" style="font-size: 200px"> </i><br>
                {% trans 'Your Shopping Cart is Empty' %}
            </div><br>
        {% endif %}
            <div class="row">
                <div class="col-md-6">
                        <div class="row mb-5">
                            <div class="col-md-6 mb-3 mb-md-0">
                                <a href="{% url 'shop:product_list' %}" class="btn btn-primary btn-md btn-block">
                                    {% trans 'Continue Shopping' %}
                                </a>
                            </div>
                            <div class="col-md-6">
                                 <a href="{% url 'cart:cart_clear' %}" class="btn btn-primary btn-md btn-block">
                                    <i class="icon-trash-o"> </i>{% trans 'Clear cart' %}
                                </a>
                            </div>
                        </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label class="text-black h4" for="coupon">{% trans 'Coupon' %}</label>
                            <p>{% blocktrans %}Enter your coupon code if you have one.{% endblocktrans %}</p>
                        </div>
                        <form action="{% url "coupons:apply" %}" method="post" class="form-inline">
                            {% csrf_token %}
                            <div class="col-md-8 mb-3 mb-md-0">
                                <input type="text" class="form-control py-3" id="coupon" name="code"
                                       placeholder="{% trans 'Coupon Code' %}">
                            </div>
                            <div class="col-md-4">
                                <input class="btn btn-primary btn-md px-4" name="coupon"
                                        type="submit" value="{% trans 'Apply Coupon' %}">
                            </div>
                        </form>
                    <br>
                        <div class="col-md-12" style="padding-top: 10px">
                            {% if cart.coupon %}
                            {% trans 'Your discont' %}
                            {{ cart.coupon.discount }}%
                            {% trans 'by code' %}
                            "{{ cart.coupon.code }}"
                            {% else %}
                                <i style="color: red" > {% trans 'Coupon is not valid' %}</i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-6 pl-5">
                    <div class="row justify-content-end">
                        <div class="col-md-7">
                            <div class="row">
                                <div class="col-md-12 text-right border-bottom mb-5">
                                    <h3 class="text-black h4 text-uppercase">{% trans 'Cart Totals' %}</h3>
                                </div>
                            </div>
                            {% if cart.coupon %}

                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">{% trans 'Subtotal' %}</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">€{{ cart.get_total_price|floatformat:"2" }}</strong>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">{% trans 'Coupon' %}</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">- €{{ cart.get_discount|floatformat:"2" }}</strong>
                                </div>
                            </div>
                        {% endif %}
                            <div class="row mb-5">
                                <div class="col-md-6">
                                    <span class="text-black">{% trans 'Total' %}</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">€{{ cart.get_total_price_after_discount|floatformat:"2" }}</strong>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <button class="btn btn-primary btn-lg btn-block"
                                            onclick="window.location='{% url "orders:order_create" %}'">
                                    <i class="icon-shopping-cart"> </i>
                                        {% blocktrans %}Proceed To Checkout{% endblocktrans %}</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}