cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('remove/', views.cart_remove, name='cart_clear'),
]

ishop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('rosetta/', include('rosetta.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Ishop{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i">
    <link rel="stylesheet" href="{% static "fonts/icomoon/style.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/aos.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">


</head>
<body>

<div class="site-wrap">
    <div class="site-navbar py-2">

      <div class="search-wrap">
        <div class="container">
          <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
          <form action="{% url 'shop:product_list' %}" method="get">
            <input type="text" class="form-control" name="s" placeholder="{% blocktrans %}Search keyword and hit enter{% endblocktrans %}...">
          </form>
        </div>
      </div>

        <div class="container">
            <div class="d-flex align-items-center justify-content-between">
                <div class="logo">
                    <div class="site-logo">
                        <a href="{% url 'shop:product_list' %}" class="js-logo-clone">Ishop</a>
                    </div>
                </div>
                <div class="main-nav d-none d-lg-block">
                    <nav class="site-navigation text-right text-md-center" role="navigation">
                        <ul class="site-menu js-clone-nav d-none d-lg-block">
                            <li><a href="{% url 'shop:product_list' %}">{% trans 'Home' %}</a></li>
                            <li class="has-children">
                                <a href="#">{% trans 'catalog' %}</a>
                                <ul class="dropdown">
                                    {% for c in categories %}
                                        <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li><a href="#">{% trans 'about' %}</a></li>
                            <li><a href="#">{% trans 'contacts' %}</a></li>
                            <li class="has-children">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                <a href="#">{% trans 'language' %}</a>
                                <ul class="dropdown">
                                    {% for language in languages %}
                                        <li><a href="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %}
                                               class="selected"{% endif %}>{{ language.name_local }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="icons">
                    <a href="#" class="icons-btn d-inline-block js-search-open">
                        <span class="icon-search"></span></a>
                    <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none">
                        <span class="icon-menu"></span></a>
                    <a href="{% url "cart:cart_detail" %}" class="icons-btn d-inline-block bag">
                        <span class="icon-shopping-bag"></span>
                        {% if cart %}<span class="number">{{ cart|length }}</span>{% endif %}
                    </a>
                </div>
            </div>
        </div>
    </div>

    {% block content %}{% endblock %}

    <footer class="site-footer">
        <div class="container"><hr>
            <div class="row">
                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

                    <div class="block-7">
                        <h3 class="footer-heading mb-4">{% trans 'About Us' %}</h3>
                        <p>{% blocktrans %} This is my first test site on python{% endblocktrans %}</p>
                    </div>

                </div>
                <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
                    <h3 class="footer-heading mb-4">{% trans 'Quick Links' %}</h3>
                    <ul class="list-unstyled">
                    {% for c in categories %}
                        <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                    {% endfor %}
                    </ul>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="block-5 mb-5">
                        <h3 class="footer-heading mb-4">{% trans 'Contact Info' %}</h3>
                        <ul class="list-unstyled">
                            <li class="address">Saint Petersburg, Nevskiy 64</li>
                            <li class="phone"><a href="tel://23923929210">+7 933 333 3333</a></li>
                            <li class="email">all@devback.online</li>
                        </ul>
                    </div>


                </div>
            </div>
            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made
                        with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com"
                                                                                 target="_blank"
                                                                                 class="text-primary">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>

            </div>
        </div>
    </footer>
</div>



<script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
<script src="{% static "js/jquery-ui.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/owl.carousel.min.js" %}"></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/aos.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
<script src="{% static "js/filter.js" %}"></script>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<script>
    var csrftoken = Cookies.get('csrftoken');

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $(document).ready(function () {
        {% block domready %}{% endblock %}
    });
</script>
</body>
</html>

templates/pagination.html
<div class="row mt-5">
    <div class="col-md-12 text-center">
        <div class="site-block-27">

        {% if page.paginator.num_pages != 1 %}
            <ul>
                {% if page.has_previous %}
                    <li><a href="?{{ s }}page={{ page.previous_page_number }}">&lt;</a></li>
                {% endif %}
                <li class="active"><span>{{ page.number }}</span></li>
                {% if page.has_next %}
                    <li><a href="?{{ s }}page={{ page.next_page_number }}">></a></li>
                {% endif %}
            </ul>
        {% endif %}
        </div>
    </div>
</div>